config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'

  get 'profiles/show'

  devise_for :users
  post 'tweets' => 'tweets#create'
  get 'tweets/new' => 'tweets#new', as: 'new/tweet'
  get 'tweets' => 'tweets#index'
  get 'tweets/:id' => 'tweets#show', as: :tweet
  get 'tweets/:id/edit' => 'tweets#edit', as: 'edit/tweet'

  get "profiles/:id" => "profiles#show", as: :profile
  get "profiles" => "profiles#index"
  put 'tweets/:id' => 'tweets#update'
  patch 'tweets/:id' => 'tweets#update'
  delete 'tweets/:id' => 'tweets#destroy'
  resources :relationships
  root 'tweets#index'
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  validates :message, presence: true, length: {maximum: 140, too_long: "A tweet is only 140 max. Everybody knows that!"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :tweets
  has_many :relationships
  has_many :friends, through: :relationships
  
validates :username, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :bio, :location])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :bio, :location])
end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @relationship = current_user.relationships.new(friend_id: params[:friend_id])
    if @relationship.save
        redirect_to request.referrer, notice: "Followed successfully"
    else
        redirect_to request.referrer, notice: "Unable to follow"
    end
  end

def destroy
  @relationship = current_user.relationships.find(params[:id])
  @relationship.destroy
  redirect_to request.referrer, notice: "No longer following."
end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def new
    @tweet = Tweet.new
  end

def create
  @tweet = Tweet.new(tweet_params)
  if @tweet.save
    redirect_to @tweet, notice: "You just tweeted!"
  else
    render :new
  end
end

def update
  if @tweet.update(tweet_params)
    redirect_to @tweet, notice: "Tweet was updated"
  else
  render :edit
end
end

def show
@tweet = Tweet.find(params[:id])
end

def index
  @t = Tweet.all
end
def edit
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path
  end
private
def set_tweet
    @tweet = Tweet.find(params[:id])
 end
def tweet_params
  params.require(:tweet).permit(:message, :user_id)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag "https://maxcdn.boostrapcdn.com/bootstrap/3.3.2/css/bootstrap/min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>

<%= yield %>

</body>
</html>

app/views/profiles/index.html.erb
<h1>All Users<h1/>
<% @users.each do |user| %>
  <%= link_to user.username, profile_path(user) %> <br />
<% end %>

app/views/profiles/show.html.erb
<%= current_user.name %>
<h1><%= @user.username %>'s Profile</h1>

<% @user.tweets.each do |tweet| %>
  <%= tweet.message %> <br />
  <% end %>

<% if current_user.friends.include?(@user) %>
  <%= link_to "Unfollow", relationship_path(current_user.relationships.find_by_friend_id(@user)), :method => :delete %>
  <% else %>
<%= link_to "Follow", relationships_path(friend_id: @user), method: :post %>
  <% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
<% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing the Tweet </h1>
<%= render 'form' %>

<%= link_to 'Back', tweets_path %>
<%= link_to 'Show', tweet_path(@tweet) %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Whatever, this is just a header</h1>

<table>
 <thead>
   <tr>
     <th>Message</th>
     <th>User</th>
     <th colspan="3"></th>
   </tr>
 </thead>
 <tbody>
   <% @t.each do |x| %>
     <tr>
       <td><%= x.message %></td>
       <td><%= x.user.username %></td>
       <td><%= link_to 'Show', x %></td>
       <td><%= link_to 'Edit', edit_tweet_path(x) %></td>
       <td><%= link_to 'Destroy', x, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     </tr>
   <% end %>
 </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user.username %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>